### ISSUE TITLE
pod, service etc. JSON responses seem correct, yet nothing is visualised in the UI

### ISSUE THREAD

**Issue by chiswicked** [spekt8/spekt8#18]
**Summary:**
Nothing's displayed in the UI despite `/pod` `/service` `/ingress` etc. json responses seem to contain all the necessary data about respective resources.

**Details:**
I'm on `18.04.1-Ubuntu` using `minikube version: v1.4.0`
As per instructions, I've downloaded the two supplied yaml files and applied them:
```
kubectl apply -f fabric8-rbac.yaml
kubectl apply -f spekt8-deployment.yaml
kubectl port-forward deployment/spekt8 3000:3000
```
Everything's running locally in the default cluster.

On http://localhost:3000/ I can see 
![Screenshot from 2019-10-13 15-45-05](https://user-images.githubusercontent.com/7613756/66717456-2cf96380-edd1-11e9-9052-d9cee78cd3f2.png)

(note the `TypeError`)

I can see all the pods, services etc. coming through in the json responses, yet nothing's displayed in the UI.

I can see the following in the logs:
```
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/server/server.js`
Listening on port 3000....
(node:39) UnhandledPromiseRejectionWarning: #<Object>
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:39) UnhandledPromiseRejectionWarning: #<Object>
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39) UnhandledPromiseRejectionWarning: #<Object>
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:39) UnhandledPromiseRejectionWarning: #<Object>
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:39) UnhandledPromiseRejectionWarning: #<Object>
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:39) UnhandledPromiseRejectionWarning: #<Object>
```
I've tried to create a different (other than default:default) role, that didn't help either, although I suspect if the json responses have the data, it's not a permission issue.

Any pointers to what I might be doing wrong and how to resolve?

**Comment by ccamacho** [comment]
Same issue.

**Comment by plord12** [comment]
Patch didn't work for me.

In the javascript console window I see :

```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at main.js:33
```

Looks like spekt8 requires at least one port in the service.

**Comment by RealKanashii** [comment]
Hi, asame here. Some calls to API seems binded to localhost. On the brorser you can see the wrong link calls:

http://localhost:3000/pod  --- timeout
http://localhost:3000/service --- timeout
http://localhost:3000/ingress --- timeout
http://localhost:3000/daemonset --- timeout

The other links are relative and have no troubles.

**Comment by RealKanashii** [comment]
![image](https://user-images.githubusercontent.com/9731708/70507841-81993080-1b2d-11ea-81a8-4bf7c80f8517.png)

**Comment by RealKanashii** [comment]
The request changing the "localhost" host by the kubernetes node ( with port forwarding) works:
![image](https://user-images.githubusercontent.com/9731708/70507951-b311fc00-1b2d-11ea-9650-e2d638df731b.png)

**Comment by v-y-a-s** [comment]
Same issue.. the API calls seem to be returning correct data

**Comment by yardenshoham** [comment]
Same issue here, why was this closed?

**Comment by CC007** [comment]
Has #20 been released yet?
